### ISSUE TITLE
ImportError: cannot import name 'ImageMultiDataset'

### ISSUE THREAD

**Issue by vikasmech** [wdhorton/protein-atlas-fastai#2]
Did they removed "ImageMultiDataset
![screen shot 2018-11-14 at 9 25 07 pm](https://user-images.githubusercontent.com/7741382/48494400-d0559780-e853-11e8-802f-a297b23f2ffa.png)
" class, i have updated to fastai.__version__
'1.0.24'

**Comment by wdhorton** [comment]
Yes, I’m working on fix now. Should be out this weekend

**Comment by adamxyang** [comment]
Hi, have you fixed this? Should we use ImageList in the latest version instead?

**Comment by adamxyang** [comment]
Found it in the datablocks  notebook. I changed ImageItemList to ImageList (in the lates version) and worked fine, thanks!
