### ISSUE TITLE
I'm getting an error 'NoneType' object has no attribute 'astype' grabbing preds.

### ISSUE THREAD

**Issue by MotorCityCobra** [wdhorton/protein-atlas-fastai#4]
Thank you for putting this together. 

I'm getting this error below while trying to grab the predictions for the trained model.  
This is with the resnet50_basic_datablocks.ipynb notebook.  

If I run 'preds,_ = learn.get_preds()' empty I get preds as a tensor.  
I try DatasetType. with single, test, train, and mro and they don't throw an error but not the preds I want, obviously.

    preds,_ = learn.get_preds(DatasetType.Test)

-------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-49-af82ae03c91a> in <module>
----> 1 preds,_ = learn.get_preds(DatasetType.Test)

~/anaconda3/lib/python3.6/site-packages/fastai/basic_train.py in get_preds(self, ds_type, with_loss, n_batch, pbar)
    209         lf = self.loss_func if with_loss else None
    210         return get_preds(self.model, self.dl(ds_type), cb_handler=CallbackHandler(self.callbacks),
--> 211                          activ=_loss_func2activ(self.loss_func), loss_func=lf, n_batch=n_batch, pbar=pbar)
    212 
    213     def pred_batch(self, ds_type:DatasetType=DatasetType.Valid, pbar:Optional[PBar]=None) -> List[Tensor]:

~/anaconda3/lib/python3.6/site-packages/fastai/basic_train.py in get_preds(model, dl, pbar, cb_handler, activ, loss_func, n_batch)
     36     "Tuple of predictions and targets, and optional losses (if `loss_func`) using `dl`, max batches `n_batch`."
     37     res = [torch.cat(o).cpu() for o in
---> 38            zip(*validate(model, dl, cb_handler=cb_handler, pbar=pbar, average=False, n_batch=n_batch))]
     39     if loss_func is not None: res.append(calc_loss(res[0], res[1], loss_func))
     40     if activ is not None: res[0] = activ(res[0])

~/anaconda3/lib/python3.6/site-packages/fastai/basic_train.py in validate(model, dl, loss_func, cb_handler, pbar, average, n_batch)
     47     with torch.no_grad():
     48         val_losses,nums = [],[]
---> 49         for xb,yb in progress_bar(dl, parent=pbar, leave=(pbar is not None)):
     50             if cb_handler: xb, yb = cb_handler.on_batch_begin(xb, yb, train=False)
     51             val_losses.append(loss_batch(model, xb, yb, loss_func, cb_handler=cb_handler))

~/anaconda3/lib/python3.6/site-packages/fastprogress/fastprogress.py in __iter__(self)
     63         self.update(0)
     64         try:
---> 65             for i,o in enumerate(self._gen):
     66                 yield o
     67                 if self.auto_update: self.update(i+1)

~/anaconda3/lib/python3.6/site-packages/fastai/basic_data.py in __iter__(self)
     45     def __iter__(self):
     46         "Process and returns items from `DataLoader`."
---> 47         for b in self.dl:
     48             y = b[1][0] if is_listy(b[1]) else b[1]
     49             if not self.skip_size1 or y.size(0) != 1: yield self.proc_batch(b)

~/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py in __next__(self)
    621         if self.rcvd_idx in self.reorder_dict:
    622             batch = self.reorder_dict.pop(self.rcvd_idx)
--> 623             return self._process_next_batch(batch)
    624 
    625         if self.batches_outstanding == 0:

~/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py in _process_next_batch(self, batch)
    656         self._put_indices()
    657         if isinstance(batch, ExceptionWrapper):
--> 658             raise batch.exc_type(batch.exc_msg)
    659         return batch
    660 

AttributeError: Traceback (most recent call last):
  File "/home/eagle/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/eagle/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/eagle/anaconda3/lib/python3.6/site-packages/fastai/data_block.py", line 415, in __getitem__
    if self.item is None: x,y = self.x[idxs],self.y[idxs]
  File "/home/eagle/anaconda3/lib/python3.6/site-packages/fastai/data_block.py", line 82, in __getitem__
    if isinstance(try_int(idxs), int): return self.get(idxs)
  File "/home/eagle/anaconda3/lib/python3.6/site-packages/fastai/vision/data.py", line 290, in get
    res = self.open(fn)
  File "/home/eagle/p4/fastai/protein-atlas-fastai/utils.py", line 16, in open_4_channel
    for color in colors]
  File "/home/eagle/p4/fastai/protein-atlas-fastai/utils.py", line 16, in <listcomp>
    for color in colors]
AttributeError: 'NoneType' object has no attribute 'astype'

**Comment by MotorCityCobra** [comment]
I did a restart and it works now.

**Comment by dkaberna** [comment]
I still get this error.  @MotorCityCobra  - any thoughts on what else I can do to resolve?
